import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} mx-auto flex h-full flex-col bg-gradient-to-t from-black via-[#180101] to-black`}
      >
        <main className="container mx-auto flex h-screen max-w-screen-lg flex-col bg-gradient-to-t from-black via-[#180101] to-black antialiased">
          <Header />
          <div className="flex h-screen w-full overflow-y-auto">
            <Sidebar className="fixed h-full w-[250px]" />
            <div className="ml-auto w-[calc(100%-250px)]">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
